#![allow(dead_code)]

use std::{
    arch::asm,
    cell::UnsafeCell,
    hint::black_box,
    mem::{self, MaybeUninit},
    sync::{atomic::Ordering, Barrier},
    thread,
};

use criterion::{criterion_group, criterion_main, Criterion};

const WRITER_THREADS: usize = 1;
const READER_THREADS: usize = 2;
const LOAD_ORDERING: Ordering = Ordering::Acquire;
const STORE_ORDERING: Ordering = Ordering::Release;
const N: u32 = 5000;

#[repr(transparent)]
struct SendSync<T>(UnsafeCell<T>);
unsafe impl<T: Send> Send for SendSync<T> {}
unsafe impl<T: Sync> Sync for SendSync<T> {}

// On AArch64, the base register of load/store/atomic instructions must be 64-bit.
// Passing a 32-bit value to `in(reg)` on AArch64 results in the upper bits
// having an undefined value, but to work correctly with ILP32 ABI, the upper
// bits must be zero, which is handled here by casting to u64. Another way to
// handle this is to pass it as a pointer and clear the upper bits inside asm,
// but it is easier to overlook than cast, which can catch overlooks by
// asm_sub_register lint.
// See also https://github.com/ARM-software/abi-aa/blob/2023Q1/aapcs64/aapcs64.rst#57pointers
//
// Except for x86_64, which can use 32-bit registers in the destination operand
// (on x86_64, we use the ptr_modifier macro to handle this), we need to do the
// same for ILP32 ABI on other 64-bit architectures. (At least, as far as I can
// see from the assembly generated by LLVM, this is also required for MIPS64 N32
// ABI. I don't know about the RISC-V s64ilp32 ABI for which a patch was
// recently submitted to the kernel, but in any case, this should be a safe
// default for such ABIs).
//
// Known architectures that have such ABI are x86_64 (X32), aarch64 (ILP32),
// mips64 (N32), and riscv64 (s64ilp32, not merged yet though). (As of
// 2023-06-05, only the former two are supported by rustc.) However, we list all
// known 64-bit architectures because similar ABIs may exist or future added for
// other architectures.
#[cfg(all(
    target_pointer_width = "32",
    any(
        target_arch = "aarch64",
        target_arch = "bpf",
        target_arch = "loongarch64",
        target_arch = "mips64",
        target_arch = "mips64r6",
        target_arch = "nvptx64",
        target_arch = "powerpc64",
        target_arch = "riscv64",
        target_arch = "s390x",
        target_arch = "sparc64",
        target_arch = "wasm64",
        target_arch = "x86_64",
    ),
))]
macro_rules! ptr_reg {
    ($ptr:ident) => {{
        let _: *const _ = $ptr; // ensure $ptr is a pointer (*mut _ or *const _)
        $ptr as u64
    }};
}
#[cfg(not(all(
    target_pointer_width = "32",
    any(
        target_arch = "aarch64",
        target_arch = "bpf",
        target_arch = "loongarch64",
        target_arch = "mips64",
        target_arch = "mips64r6",
        target_arch = "nvptx64",
        target_arch = "powerpc64",
        target_arch = "riscv64",
        target_arch = "s390x",
        target_arch = "sparc64",
        target_arch = "wasm64",
        target_arch = "x86_64",
    ),
)))]
macro_rules! ptr_reg {
    ($ptr:ident) => {{
        let _: *const _ = $ptr; // ensure $ptr is a pointer (*mut _ or *const _)
        $ptr // cast is unnecessary here.
    }};
}

#[inline]
pub unsafe fn atomic_load_memcpy<T>(mut src: *const MaybeUninit<T>, mut out: *mut MaybeUninit<T>) {
    unsafe {
        macro_rules! ldrb_ {
            ($offset:tt $($tt:tt)*) => {
                concat!(
                    "\n",
                    "ldrb {tmp:w}, [{src}", $offset, "]", "\n",
                    "ldrb {tmp:w}, [{out}", $offset, "]",
                    ldrb_!($($tt)*),
                )
            };
            () => {
                "\n"
            };
        }
        macro_rules! ldrb {
            ($($tt:tt)*) => {
                asm!(
                    ldrb_!($($tt)*),
                    src = in(reg) ptr_reg!(src),
                    out = in(reg) ptr_reg!(out),
                    tmp = out(reg) _,
                    options(nostack, preserves_flags),
                )
            };
        }
        macro_rules! ldrh_ {
            ($offset:tt $($tt:tt)*) => {
                concat!(
                    "\n",
                    "ldrh {tmp:w}, [{src}", $offset, "]", "\n",
                    "ldrh {tmp:w}, [{out}", $offset, "]",
                    ldrh_!($($tt)*),
                )
            };
            () => {
                "\n"
            };
        }
        macro_rules! ldrh {
            ($($tt:tt)*) => {
                asm!(
                    ldrh_!($($tt)*),
                    src = in(reg) ptr_reg!(src),
                    out = in(reg) ptr_reg!(out),
                    tmp = out(reg) _,
                    options(nostack, preserves_flags),
                )
            };
        }
        macro_rules! ldr32_ {
            ($offset:tt $($tt:tt)*) => {
                concat!(
                    "\n",
                    "ldr {tmp:w}, [{src}", $offset, "]", "\n",
                    "ldr {tmp:w}, [{out}", $offset, "]",
                    ldr32_!($($tt)*),
                )
            };
            () => {
                "\n"
            };
        }
        macro_rules! ldr32 {
            ($($tt:tt)*) => {
                asm!(
                    ldr32_!($($tt)*),
                    src = in(reg) ptr_reg!(src),
                    out = in(reg) ptr_reg!(out),
                    tmp = out(reg) _,
                    options(nostack, preserves_flags),
                )
            };
        }
        macro_rules! ldr64_ {
            ($offset:tt $($tt:tt)*) => {
                concat!(
                    "\n",
                    "ldr {tmp}, [{src}", $offset, "]", "\n",
                    "ldr {tmp}, [{out}", $offset, "]",
                    ldr64_!($($tt)*),
                )
            };
            () => {
                "\n"
            };
        }
        macro_rules! ldr64 {
            ($($tt:tt)*) => {
                asm!(
                    ldr64_!($($tt)*),
                    src = in(reg) ptr_reg!(src),
                    out = in(reg) ptr_reg!(out),
                    tmp = out(reg) _,
                    options(nostack, preserves_flags),
                )
            };
        }
        macro_rules! ldp_ {
            ($offset:tt $($tt:tt)*) => {
                concat!(
                    "\n",
                    "ldp {tmp_lo}, {tmp_hi}, [{src}", $offset, "]", "\n",
                    "stp {tmp_lo}, {tmp_hi}, [{out}", $offset, "]",
                    ldp_!($($tt)*),
                )
            };
            () => {
                "\n"
            };
        }
        macro_rules! ldp {
            ($($tt:tt)*) => {
                asm!(
                    ldp_!($($tt)*),
                    src = in(reg) ptr_reg!(src),
                    out = in(reg) ptr_reg!(out),
                    tmp_hi = out(reg) _,
                    tmp_lo = out(reg) _,
                    options(nostack, preserves_flags),
                )
            };
        }
        if mem::size_of::<T>() == 0 {
            return;
        }
        if mem::align_of::<T>() < 8 && mem::size_of::<T>() >= 8 * 4 {
            let offset = src.cast::<u8>().align_offset(8);
            let mut remaining = mem::size_of::<T>();
            if remaining >= offset {
                for _ in 0..offset {
                    ldrb!("");
                    remaining -= 1;
                    src = src.add(1);
                }
                while remaining >= 8 {
                    ldr64!("");
                    remaining -= 8;
                    src = src.add(8);
                }
                for _ in 0..remaining {
                    ldrb!("");
                    src = src.add(1);
                }
                return;
            }
        }
        if mem::align_of::<T>() >= 16 {
            if mem::size_of::<T>() / 16 < 8 {
                match mem::size_of::<T>() / 16 {
                    1 => ldp!(""),
                    2 => ldp!("" ",16"),
                    3 => ldp!("" ",16" ",32"),
                    4 => ldp!("" ",16" ",32" ",48"),
                    5 => ldp!("" ",16" ",32" ",48" ",64"),
                    6 => ldp!("" ",16" ",32" ",48" ",64" ",80"),
                    7 => ldp!("" ",16" ",32" ",48" ",64" ",80" ",96"),
                    _ => unreachable!(),
                }
                return;
            }
            for _ in 0..(mem::size_of::<T>() / 16 / 8) - 1 {
                ldp!("" ",16" ",32" ",48" ",64" ",80" ",96" ",112");
                src = src.cast::<u8>().add(16 * 8).cast::<MaybeUninit<T>>();
                out = out.cast::<u8>().add(16 * 8).cast::<MaybeUninit<T>>();
            }
            ldp!("" ",16" ",32" ",48" ",64" ",80" ",96" ",112");
            if mem::size_of::<T>() / 16 % 8 == 0 {
                return;
            }
            src = src.cast::<u8>().add(16 * 8).cast::<MaybeUninit<T>>();
            out = out.cast::<u8>().add(16 * 8).cast::<MaybeUninit<T>>();
            match mem::size_of::<T>() / 16 % 8 {
                1 => ldp!(""),
                2 => ldp!("" ",16"),
                3 => ldp!("" ",16" ",32"),
                4 => ldp!("" ",16" ",32" ",48"),
                5 => ldp!("" ",16" ",32" ",48" ",64"),
                6 => ldp!("" ",16" ",32" ",48" ",64" ",80"),
                7 => ldp!("" ",16" ",32" ",48" ",64" ",80" ",96"),
                _ => unreachable!(),
            }
            return;
        }
        if mem::align_of::<T>() >= 8 {
            if mem::size_of::<T>() / 8 < 8 {
                match mem::size_of::<T>() / 8 {
                    1 => ldr64!(""),
                    2 => ldr64!("" ",8"),
                    3 => ldr64!("" ",8" ",16"),
                    4 => ldr64!("" ",8" ",16" ",24"),
                    5 => ldr64!("" ",8" ",16" ",24" ",32"),
                    6 => ldr64!("" ",8" ",16" ",24" ",32" ",40"),
                    7 => ldr64!("" ",8" ",16" ",24" ",32" ",40" ",48"),
                    _ => unreachable!(),
                }
                return;
            }
            for _ in 0..(mem::size_of::<T>() / 8 / 8) - 1 {
                ldr64!("" ",8" ",16" ",24" ",32" ",40" ",48" ",56");
                src = src.cast::<u8>().add(8 * 8).cast::<MaybeUninit<T>>();
                out = out.cast::<u8>().add(8 * 8).cast::<MaybeUninit<T>>();
            }
            ldr64!("" ",8" ",16" ",24" ",32" ",40" ",48" ",56");
            if mem::size_of::<T>() / 8 % 8 == 0 {
                return;
            }
            src = src.cast::<u8>().add(8 * 8).cast::<MaybeUninit<T>>();
            out = out.cast::<u8>().add(8 * 8).cast::<MaybeUninit<T>>();
            match mem::size_of::<T>() / 8 % 8 {
                1 => ldr64!(""),
                2 => ldr64!("" ",8"),
                3 => ldr64!("" ",8" ",16"),
                4 => ldr64!("" ",8" ",16" ",24"),
                5 => ldr64!("" ",8" ",16" ",24" ",32"),
                6 => ldr64!("" ",8" ",16" ",24" ",32" ",40"),
                7 => ldr64!("" ",8" ",16" ",24" ",32" ",40" ",48"),
                _ => unreachable!(),
            }
            return;
        }
        if mem::align_of::<T>() >= 4 {
            if mem::size_of::<T>() / 4 < 8 {
                match mem::size_of::<T>() / 4 {
                    1 => ldr32!(""),
                    2 => ldr32!("" ",4"),
                    3 => ldr32!("" ",4" ",8"),
                    4 => ldr32!("" ",4" ",8" ",12"),
                    5 => ldr32!("" ",4" ",8" ",12" ",16"),
                    6 => ldr32!("" ",4" ",8" ",12" ",16" ",20"),
                    7 => ldr32!("" ",4" ",8" ",12" ",16" ",20" ",24"),
                    _ => unreachable!(),
                }
                return;
            }
            for _ in 0..(mem::size_of::<T>() / 4 / 8) - 1 {
                ldr32!("" ",4" ",8" ",12" ",16" ",20" ",24" ",28");
                src = src.cast::<u8>().add(4 * 8).cast::<MaybeUninit<T>>();
                out = out.cast::<u8>().add(4 * 8).cast::<MaybeUninit<T>>();
            }
            ldr32!("" ",4" ",8" ",12" ",16" ",20" ",24" ",28");
            if mem::size_of::<T>() / 4 % 8 == 0 {
                return;
            }
            src = src.cast::<u8>().add(4 * 8).cast::<MaybeUninit<T>>();
            out = out.cast::<u8>().add(4 * 8).cast::<MaybeUninit<T>>();
            match mem::size_of::<T>() / 4 % 8 {
                1 => ldr32!(""),
                2 => ldr32!("" ",4"),
                3 => ldr32!("" ",4" ",8"),
                4 => ldr32!("" ",4" ",8" ",12"),
                5 => ldr32!("" ",4" ",8" ",12" ",16"),
                6 => ldr32!("" ",4" ",8" ",12" ",16" ",20"),
                7 => ldr32!("" ",4" ",8" ",12" ",16" ",20" ",24"),
                _ => unreachable!(),
            }
            return;
        }
        if mem::align_of::<T>() >= 2 {
            if mem::size_of::<T>() / 2 < 8 {
                match mem::size_of::<T>() / 2 {
                    1 => ldrh!(""),
                    2 => ldrh!("" ",2"),
                    3 => ldrh!("" ",2" ",4"),
                    4 => ldrh!("" ",2" ",4" ",6"),
                    5 => ldrh!("" ",2" ",4" ",6" ",8"),
                    6 => ldrh!("" ",2" ",4" ",6" ",8" ",10"),
                    7 => ldrh!("" ",2" ",4" ",6" ",8" ",10" ",12"),
                    _ => unreachable!(),
                }
                return;
            }
            for _ in 0..(mem::size_of::<T>() / 2 / 8) - 1 {
                ldrh!("" ",2" ",4" ",6" ",8" ",10" ",12" ",14");
                src = src.cast::<u8>().add(2 * 8).cast::<MaybeUninit<T>>();
                out = out.cast::<u8>().add(2 * 8).cast::<MaybeUninit<T>>();
            }
            ldrh!("" ",2" ",4" ",6" ",8" ",10" ",12" ",14");
            if mem::size_of::<T>() / 2 % 8 == 0 {
                return;
            }
            src = src.cast::<u8>().add(2 * 8).cast::<MaybeUninit<T>>();
            out = out.cast::<u8>().add(2 * 8).cast::<MaybeUninit<T>>();
            match mem::size_of::<T>() / 2 % 8 {
                1 => ldrh!(""),
                2 => ldrh!("" ",2"),
                3 => ldrh!("" ",2" ",4"),
                4 => ldrh!("" ",2" ",4" ",6"),
                5 => ldrh!("" ",2" ",4" ",6" ",8"),
                6 => ldrh!("" ",2" ",4" ",6" ",8" ",10"),
                7 => ldrh!("" ",2" ",4" ",6" ",8" ",10" ",12"),
                _ => unreachable!(),
            }
            return;
        }
        if mem::size_of::<T>() < 8 {
            match mem::size_of::<T>() {
                1 => ldrb!(""),
                2 => ldrb!("" ",1"),
                3 => ldrb!("" ",1" ",2"),
                4 => ldrb!("" ",1" ",2" ",3"),
                5 => ldrb!("" ",1" ",2" ",3" ",4"),
                6 => ldrb!("" ",1" ",2" ",3" ",4" ",5"),
                7 => ldrb!("" ",1" ",2" ",3" ",4" ",5" ",6"),
                _ => unreachable!(),
            }
            return;
        }
        for _ in 0..(mem::size_of::<T>() / 8) - 1 {
            ldrb!("" ",1" ",2" ",3" ",4" ",5" ",6" ",7");
            src = src.cast::<u8>().add(8).cast::<MaybeUninit<T>>();
            out = out.cast::<u8>().add(8).cast::<MaybeUninit<T>>();
        }
        ldrh!("" ",2" ",4" ",6" ",8" ",10" ",12" ",14");
        if mem::size_of::<T>() % 8 == 0 {
            return;
        }
        src = src.cast::<u8>().add(8).cast::<MaybeUninit<T>>();
        out = out.cast::<u8>().add(8).cast::<MaybeUninit<T>>();
        match mem::size_of::<T>() % 8 {
            1 => ldrb!(""),
            2 => ldrb!("" ",1"),
            3 => ldrb!("" ",1" ",2"),
            4 => ldrb!("" ",1" ",2" ",3"),
            5 => ldrb!("" ",1" ",2" ",3" ",4"),
            6 => ldrb!("" ",1" ",2" ",3" ",4" ",5"),
            7 => ldrb!("" ",1" ",2" ",3" ",4" ",5" ",6"),
            _ => unreachable!(),
        }
    }
}
#[inline]
pub unsafe fn atomic_load<T>(src: *const T, order: Ordering) -> core::mem::MaybeUninit<T> {
    // SAFETY: the caller must uphold the safety contract for `atomic_load`.
    let mut out = MaybeUninit::uninit();
    unsafe { atomic_load_memcpy(src.cast::<MaybeUninit<T>>(), &mut out) };
    match order {
        Ordering::Relaxed => { /* no-op */ }
        _ => core::sync::atomic::fence(order),
    }
    out
}

fn bench_load<T: Copy + Send + Sync>(v: &SendSync<T>, _val: T) {
    unsafe {
        // black_box(atomic_memcpy::atomic_load(v.0.get(), LOAD_ORDERING).assume_init());
        black_box(atomic_load(v.0.get(), LOAD_ORDERING).assume_init());
    }
}
fn bench_store<T: Copy + Send + Sync>(v: &SendSync<T>, val: T) {
    unsafe {
        atomic_memcpy::atomic_store(v.0.get(), val, STORE_ORDERING);
    }
}
fn bench_concurrent_load_store<T: Copy + Send + Sync>(v: &SendSync<T>, val: T) {
    let barrier = Barrier::new(WRITER_THREADS + READER_THREADS);
    thread::scope(|s| {
        for _ in 0..READER_THREADS {
            s.spawn(|| {
                barrier.wait();
                for _ in 0..N {
                    unsafe {
                        black_box(
                            atomic_memcpy::atomic_load(v.0.get(), LOAD_ORDERING).assume_init(),
                        );
                    }
                }
            });
        }
        for _ in 0..WRITER_THREADS {
            s.spawn(|| {
                barrier.wait();
                for _ in 0..N {
                    unsafe {
                        atomic_memcpy::atomic_store(v.0.get(), val, STORE_ORDERING);
                    }
                }
            });
        }
    });
}

#[derive(Clone, Copy, Default)]
#[repr(C, align(1))]
struct Align1<T>(T);
#[derive(Clone, Copy, Default)]
#[repr(C, align(2))]
struct Align2<T>(T);
#[derive(Clone, Copy, Default)]
#[repr(C, align(4))]
struct Align4<T>(T);
#[derive(Clone, Copy, Default)]
#[repr(C, align(8))]
struct Align8<T>(T);
#[derive(Clone, Copy, Default)]
#[repr(C, align(16))]
struct Align16<T>(T);

macro_rules! b {
    ($b:ident, $bench_fn:ident, $v:expr) => {
        let val1 = black_box($v);
        let val2 = black_box($v);
        $b.iter(|| {
            let v = SendSync(UnsafeCell::new(val1));
            $bench_fn(&v, val2);
            v
        });
    };
}
macro_rules! bg {
    ($c:ident, $group_name:expr, $bench_fn:ident, $v:expr) => {{
        let mut g = $c.benchmark_group($group_name);
        g.bench_function("align1", |b| {
            b!(b, $bench_fn, Align1($v));
        });
        g.bench_function("align2", |b| {
            b!(b, $bench_fn, Align2($v));
        });
        g.bench_function("align4", |b| {
            b!(b, $bench_fn, Align4($v));
        });
        g.bench_function("align8", |b| {
            b!(b, $bench_fn, Align8($v));
        });
        g.bench_function("align16", |b| {
            b!(b, $bench_fn, Align16($v));
        });
    }};
}

fn bench_atomic_copy(c: &mut Criterion) {
    assert_eq!(mem::align_of::<Align1<[u8; 2048]>>(), 1);
    assert_eq!(mem::align_of::<Align2<[u8; 2048]>>(), 2);
    assert_eq!(mem::align_of::<Align4<[u8; 2048]>>(), 4);
    assert_eq!(mem::align_of::<Align8<[u8; 2048]>>(), 8);
    assert_eq!(mem::align_of::<Align16<[u8; 2048]>>(), 16);

    bg!(c, "load_u8x8", bench_load, [0u8; 8]);
    bg!(c, "load_u8x16", bench_load, [0u8; 16]);
    bg!(c, "load_u8x32", bench_load, [0u8; 32]);
    bg!(c, "load_u8x64", bench_load, [0u8; 64]);
    bg!(c, "load_u8x256", bench_load, [0u8; 256]);

    // bg!(c, "store_u8x16", bench_store, [0u8; 16]);
    // bg!(c, "store_u8x32", bench_store, [0u8; 32]);
    // bg!(c, "store_u8x64", bench_store, [0u8; 64]);
    // bg!(c, "store_u8x256", bench_store, [0u8; 256]);

    // bg!(c, "concurrent_load_store_u8x16", bench_concurrent_load_store, [0u8; 16]);
    // bg!(c, "concurrent_load_store_u8x64", bench_concurrent_load_store, [0u8; 64]);
    // bg!(c, "concurrent_load_store_u8x256", bench_concurrent_load_store, [0u8; 256]);
}

criterion_group!(benches, bench_atomic_copy);
criterion_main!(benches);
