#![allow(clippy::missing_safety_doc, clippy::undocumented_unsafe_blocks, clippy::too_many_lines)]

use core::{
    arch::asm,
    mem::{self, MaybeUninit},
    sync::atomic::{self, Ordering},
};

#[inline]
pub unsafe fn atomic_load<T>(src: *const T, order: Ordering) -> MaybeUninit<T> {
    crate::assert_load_ordering(order);
    let mut out = MaybeUninit::uninit();
    unsafe { atomic_load_memcpy(src.cast::<MaybeUninit<T>>(), &mut out) };
    match order {
        Ordering::Relaxed => { /* no-op */ }
        _ => atomic::fence(order),
    }
    out
}

#[allow(clippy::needless_pass_by_value)]
#[inline]
pub unsafe fn atomic_store<T>(dst: *mut T, val: T, order: Ordering) {
    crate::assert_store_ordering(order);
    match order {
        Ordering::Relaxed => { /* no-op */ }
        _ => atomic::fence(order),
    }
    // SAFETY: the caller must uphold the safety contract for `atomic_load`.
    unsafe {
        atomic_load_memcpy(&MaybeUninit::new(val), dst.cast::<MaybeUninit<T>>());
    }
}

// On AArch64, the base register of load/store/atomic instructions must be 64-bit.
// Passing a 32-bit value to `in(reg)` on AArch64 results in the upper bits
// having an undefined value, but to work correctly with ILP32 ABI, the upper
// bits must be zero, which is handled here by casting to u64. Another way to
// handle this is to pass it as a pointer and clear the upper bits inside asm,
// but it is easier to overlook than cast, which can catch overlooks by
// asm_sub_register lint.
// See also https://github.com/ARM-software/abi-aa/blob/2023Q1/aapcs64/aapcs64.rst#57pointers
//
// Except for x86_64, which can use 32-bit registers in the destination operand
// (on x86_64, we use the ptr_modifier macro to handle this), we need to do the
// same for ILP32 ABI on other 64-bit architectures. (At least, as far as I can
// see from the assembly generated by LLVM, this is also required for MIPS64 N32
// ABI. I don't know about the RISC-V s64ilp32 ABI for which a patch was
// recently submitted to the kernel, but in any case, this should be a safe
// default for such ABIs).
//
// Known architectures that have such ABI are x86_64 (X32), aarch64 (ILP32),
// mips64 (N32), and riscv64 (s64ilp32, not merged yet though). (As of
// 2023-06-05, only the former two are supported by rustc.) However, we list all
// known 64-bit architectures because similar ABIs may exist or future added for
// other architectures.
#[cfg(all(
    target_pointer_width = "32",
    any(
        target_arch = "aarch64",
        target_arch = "bpf",
        target_arch = "loongarch64",
        target_arch = "mips64",
        target_arch = "mips64r6",
        target_arch = "nvptx64",
        target_arch = "powerpc64",
        target_arch = "riscv64",
        target_arch = "s390x",
        target_arch = "sparc64",
        target_arch = "wasm64",
        target_arch = "x86_64",
    ),
))]
macro_rules! ptr_reg {
    ($ptr:ident) => {{
        let _: *const _ = $ptr; // ensure $ptr is a pointer (*mut _ or *const _)
        $ptr as u64
    }};
}
#[cfg(not(all(
    target_pointer_width = "32",
    any(
        target_arch = "aarch64",
        target_arch = "bpf",
        target_arch = "loongarch64",
        target_arch = "mips64",
        target_arch = "mips64r6",
        target_arch = "nvptx64",
        target_arch = "powerpc64",
        target_arch = "riscv64",
        target_arch = "s390x",
        target_arch = "sparc64",
        target_arch = "wasm64",
        target_arch = "x86_64",
    ),
)))]
macro_rules! ptr_reg {
    ($ptr:ident) => {{
        let _: *const _ = $ptr; // ensure $ptr is a pointer (*mut _ or *const _)
        $ptr // cast is unnecessary here.
    }};
}

macro_rules! memcpy1_ {
    ($offset:tt $($tt:tt)*) => {
        concat!(
            "\n",
            "ldrb {tmp:w}, [{src}", $offset, "]", "\n",
            "strb {tmp:w}, [{dst}", $offset, "]",
            memcpy1_!($($tt)*),
        )
    };
    () => {
        "\n"
    };
}
macro_rules! memcpy1 {
    ($src:tt, $dst:tt, $($tt:tt)*) => {
        asm!(
            memcpy1_!($($tt)*),
            src = in(reg) ptr_reg!($src),
            dst = in(reg) ptr_reg!($dst),
            tmp = out(reg) _,
            options(nostack, preserves_flags),
        )
    };
}
macro_rules! memcpy2_ {
    ($offset:tt $($tt:tt)*) => {
        concat!(
            "\n",
            "ldrh {tmp:w}, [{src}", $offset, "]", "\n",
            "strh {tmp:w}, [{dst}", $offset, "]",
            memcpy2_!($($tt)*),
        )
    };
    () => {
        "\n"
    };
}
macro_rules! memcpy2 {
    ($src:tt, $dst:tt, $($tt:tt)*) => {
        asm!(
            memcpy2_!($($tt)*),
            src = in(reg) ptr_reg!($src),
            dst = in(reg) ptr_reg!($dst),
            tmp = out(reg) _,
            options(nostack, preserves_flags),
        )
    };
}
macro_rules! memcpy4_ {
    ($offset:tt $($tt:tt)*) => {
        concat!(
            "\n",
            "ldr {tmp:w}, [{src}", $offset, "]", "\n",
            "str {tmp:w}, [{dst}", $offset, "]",
            memcpy4_!($($tt)*),
        )
    };
    () => {
        "\n"
    };
}
macro_rules! memcpy4 {
    ($src:tt, $dst:tt, $($tt:tt)*) => {
        asm!(
            memcpy4_!($($tt)*),
            src = in(reg) ptr_reg!($src),
            dst = in(reg) ptr_reg!($dst),
            tmp = out(reg) _,
            options(nostack, preserves_flags),
        )
    };
}
macro_rules! memcpy8_ {
    ($offset:tt $($tt:tt)*) => {
        concat!(
            "\n",
            "ldr {tmp}, [{src}", $offset, "]", "\n",
            "str {tmp}, [{dst}", $offset, "]",
            memcpy8_!($($tt)*),
        )
    };
    () => {
        "\n"
    };
}
macro_rules! memcpy8 {
    ($src:tt, $dst:tt, $($tt:tt)*) => {
        asm!(
            memcpy8_!($($tt)*),
            src = in(reg) ptr_reg!($src),
            dst = in(reg) ptr_reg!($dst),
            tmp = out(reg) _,
            options(nostack, preserves_flags),
        )
    };
}
macro_rules! memcpy16_ {
    ($offset:tt $($tt:tt)*) => {
        concat!(
            "\n",
            "ldp {tmp_lo}, {tmp_hi}, [{src}", $offset, "]", "\n",
            "stp {tmp_lo}, {tmp_hi}, [{dst}", $offset, "]",
            memcpy16_!($($tt)*),
        )
    };
    () => {
        "\n"
    };
}
macro_rules! memcpy16 {
    ($src:tt, $dst:tt, $($tt:tt)*) => {
        asm!(
            memcpy16_!($($tt)*),
            src = in(reg) ptr_reg!($src),
            dst = in(reg) ptr_reg!($dst),
            tmp_hi = out(reg) _,
            tmp_lo = out(reg) _,
            options(nostack, preserves_flags),
        )
    };
}

#[inline]
pub unsafe fn atomic_load_memcpy<T>(mut src: *const MaybeUninit<T>, mut out: *mut MaybeUninit<T>) {
    unsafe {
        if mem::size_of::<T>() == 0 {
            return;
        }
        if mem::align_of::<T>() < 8 && mem::size_of::<T>() >= 8 * 2 {
            let offset = src.cast::<u8>().align_offset(8);
            let mut remaining = mem::size_of::<T>();
            if remaining >= offset {
                let mut pos = 0;
                if mem::align_of::<T>() >= 4 {
                    for _ in 0..offset / 4 {
                        memcpy4_const(src.cast::<u8>().add(pos), out.cast::<u8>().add(pos), 1);
                        remaining -= 4;
                        pos += 4;
                    }
                    while remaining >= 8 {
                        memcpy8_const(src.cast::<u8>().add(pos), out.cast::<u8>().add(pos), 1);
                        remaining -= 8;
                        pos += 8;
                    }
                    for _ in 0..remaining / 4 {
                        memcpy4_const(src.cast::<u8>().add(pos), out.cast::<u8>().add(pos), 1);
                        pos += 4;
                    }
                    return;
                }
                if mem::align_of::<T>() >= 2 {
                    for _ in 0..offset / 2 {
                        memcpy2_const(src.cast::<u8>().add(pos), out.cast::<u8>().add(pos), 1);
                        remaining -= 2;
                        pos += 2;
                    }
                    while remaining >= 8 {
                        memcpy8_const(src.cast::<u8>().add(pos), out.cast::<u8>().add(pos), 1);
                        remaining -= 8;
                        pos += 8;
                    }
                    for _ in 0..remaining / 2 {
                        memcpy2_const(src.cast::<u8>().add(pos), out.cast::<u8>().add(pos), 1);
                        pos += 2;
                    }
                    return;
                }
                for _ in 0..offset {
                    memcpy1_const(src.cast::<u8>().add(pos), out.cast::<u8>().add(pos), 1);
                    remaining -= 1;
                    pos += 1;
                }
                while remaining >= 8 {
                    memcpy8_const(src.cast::<u8>().add(pos), out.cast::<u8>().add(pos), 1);
                    remaining -= 8;
                    pos += 8;
                }
                for _ in 0..remaining {
                    memcpy1_const(src.cast::<u8>().add(pos), out.cast::<u8>().add(pos), 1);
                    pos += 1;
                }
                return;
            }
        }
        if mem::align_of::<T>() >= 16 {
            if mem::size_of::<T>() / 16 < 8 {
                memcpy16_const(src.cast::<u8>(), out.cast::<u8>(), mem::size_of::<T>() / 16);
                return;
            }
            for _ in 0..(mem::size_of::<T>() / 16 / 8) - 1 {
                memcpy16_const(src.cast::<u8>(), out.cast::<u8>(), 8);
                src = src.cast::<u8>().add(16 * 8).cast::<MaybeUninit<T>>();
                out = out.cast::<u8>().add(16 * 8).cast::<MaybeUninit<T>>();
            }
            memcpy16_const(src.cast::<u8>(), out.cast::<u8>(), 8);
            if mem::size_of::<T>() / 16 % 8 == 0 {
                return;
            }
            src = src.cast::<u8>().add(16 * 8).cast::<MaybeUninit<T>>();
            out = out.cast::<u8>().add(16 * 8).cast::<MaybeUninit<T>>();
            memcpy16_const(src.cast::<u8>(), out.cast::<u8>(), mem::size_of::<T>() / 16 % 8);
            return;
        }
        if mem::align_of::<T>() >= 8 {
            if mem::size_of::<T>() / 8 < 8 {
                memcpy8_const(src.cast::<u8>(), out.cast::<u8>(), mem::size_of::<T>() / 8);
                return;
            }
            for _ in 0..(mem::size_of::<T>() / 8 / 8) - 1 {
                memcpy8_const(src.cast::<u8>(), out.cast::<u8>(), 8);
                src = src.cast::<u8>().add(8 * 8).cast::<MaybeUninit<T>>();
                out = out.cast::<u8>().add(8 * 8).cast::<MaybeUninit<T>>();
            }
            memcpy8_const(src.cast::<u8>(), out.cast::<u8>(), 8);
            if mem::size_of::<T>() / 8 % 8 == 0 {
                return;
            }
            src = src.cast::<u8>().add(8 * 8).cast::<MaybeUninit<T>>();
            out = out.cast::<u8>().add(8 * 8).cast::<MaybeUninit<T>>();
            memcpy8_const(src.cast::<u8>(), out.cast::<u8>(), mem::size_of::<T>() / 8 % 8);
            return;
        }
        if mem::align_of::<T>() >= 4 {
            if mem::size_of::<T>() / 4 < 8 {
                memcpy4_const(src.cast::<u8>(), out.cast::<u8>(), mem::size_of::<T>() / 4);
                return;
            }
            for _ in 0..(mem::size_of::<T>() / 4 / 8) - 1 {
                memcpy4_const(src.cast::<u8>(), out.cast::<u8>(), 8);
                src = src.cast::<u8>().add(4 * 8).cast::<MaybeUninit<T>>();
                out = out.cast::<u8>().add(4 * 8).cast::<MaybeUninit<T>>();
            }
            memcpy4_const(src.cast::<u8>(), out.cast::<u8>(), 8);
            if mem::size_of::<T>() / 4 % 8 == 0 {
                return;
            }
            src = src.cast::<u8>().add(4 * 8).cast::<MaybeUninit<T>>();
            out = out.cast::<u8>().add(4 * 8).cast::<MaybeUninit<T>>();
            memcpy4_const(src.cast::<u8>(), out.cast::<u8>(), mem::size_of::<T>() / 4 % 8);
            return;
        }
        if mem::align_of::<T>() >= 2 {
            if mem::size_of::<T>() / 2 < 8 {
                memcpy2_const(src.cast::<u8>(), out.cast::<u8>(), mem::size_of::<T>() / 2);
                return;
            }
            for _ in 0..(mem::size_of::<T>() / 2 / 8) - 1 {
                memcpy2_const(src.cast::<u8>(), out.cast::<u8>(), 8);
                src = src.cast::<u8>().add(2 * 8).cast::<MaybeUninit<T>>();
                out = out.cast::<u8>().add(2 * 8).cast::<MaybeUninit<T>>();
            }
            memcpy2_const(src.cast::<u8>(), out.cast::<u8>(), 8);
            if mem::size_of::<T>() / 2 % 8 == 0 {
                return;
            }
            src = src.cast::<u8>().add(2 * 8).cast::<MaybeUninit<T>>();
            out = out.cast::<u8>().add(2 * 8).cast::<MaybeUninit<T>>();
            memcpy2_const(src.cast::<u8>(), out.cast::<u8>(), mem::size_of::<T>() / 2 % 8);
            return;
        }
        if mem::size_of::<T>() < 8 {
            memcpy1_const(src.cast::<u8>(), out.cast::<u8>(), mem::size_of::<T>());
            return;
        }
        for _ in 0..(mem::size_of::<T>() / 8) - 1 {
            memcpy1_const(src.cast::<u8>(), out.cast::<u8>(), 8);
            src = src.cast::<u8>().add(8).cast::<MaybeUninit<T>>();
            out = out.cast::<u8>().add(8).cast::<MaybeUninit<T>>();
        }
        memcpy1_const(src.cast::<u8>(), out.cast::<u8>(), 8);
        if mem::size_of::<T>() % 8 == 0 {
            return;
        }
        src = src.cast::<u8>().add(8).cast::<MaybeUninit<T>>();
        out = out.cast::<u8>().add(8).cast::<MaybeUninit<T>>();
        memcpy1_const(src.cast::<u8>(), out.cast::<u8>(), mem::size_of::<T>() % 8);
    }
}

#[inline]
unsafe fn memcpy1_const(src: *const u8, dst: *mut u8, size: usize) {
    unsafe {
        match size {
            1 => memcpy1!(src, dst, ""),
            2 => memcpy1!(src, dst, "" ",1"),
            3 => memcpy1!(src, dst, "" ",1" ",2"),
            4 => memcpy1!(src, dst, "" ",1" ",2" ",3"),
            5 => memcpy1!(src, dst, "" ",1" ",2" ",3" ",4"),
            6 => memcpy1!(src, dst, "" ",1" ",2" ",3" ",4" ",5"),
            7 => memcpy1!(src, dst, "" ",1" ",2" ",3" ",4" ",5" ",6"),
            8 => memcpy1!(src, dst, "" ",1" ",2" ",3" ",4" ",5" ",6" ",7"),
            _ => unreachable!(),
        }
    }
}
#[inline]
unsafe fn memcpy2_const(src: *const u8, dst: *mut u8, size: usize) {
    unsafe {
        match size {
            1 => memcpy2!(src, dst, ""),
            2 => memcpy2!(src, dst, "" ",2"),
            3 => memcpy2!(src, dst, "" ",2" ",4"),
            4 => memcpy2!(src, dst, "" ",2" ",4" ",6"),
            5 => memcpy2!(src, dst, "" ",2" ",4" ",6" ",8"),
            6 => memcpy2!(src, dst, "" ",2" ",4" ",6" ",8" ",10"),
            7 => memcpy2!(src, dst, "" ",2" ",4" ",6" ",8" ",10" ",12"),
            8 => memcpy2!(src, dst, "" ",2" ",4" ",6" ",8" ",10" ",12" ",14"),
            _ => unreachable!(),
        }
    }
}
#[inline]
unsafe fn memcpy4_const(src: *const u8, dst: *mut u8, size: usize) {
    unsafe {
        match size {
            1 => memcpy4!(src, dst, ""),
            2 => memcpy4!(src, dst, "" ",4"),
            3 => memcpy4!(src, dst, "" ",4" ",8"),
            4 => memcpy4!(src, dst, "" ",4" ",8" ",12"),
            5 => memcpy4!(src, dst, "" ",4" ",8" ",12" ",16"),
            6 => memcpy4!(src, dst, "" ",4" ",8" ",12" ",16" ",20"),
            7 => memcpy4!(src, dst, "" ",4" ",8" ",12" ",16" ",20" ",24"),
            8 => memcpy4!(src, dst, "" ",4" ",8" ",12" ",16" ",20" ",24" ",28"),
            _ => unreachable!(),
        }
    }
}
#[inline]
unsafe fn memcpy8_const(src: *const u8, dst: *mut u8, size: usize) {
    unsafe {
        match size {
            1 => memcpy8!(src, dst, ""),
            2 => memcpy8!(src, dst, "" ",8"),
            3 => memcpy8!(src, dst, "" ",8" ",16"),
            4 => memcpy8!(src, dst, "" ",8" ",16" ",24"),
            5 => memcpy8!(src, dst, "" ",8" ",16" ",24" ",32"),
            6 => memcpy8!(src, dst, "" ",8" ",16" ",24" ",32" ",40"),
            7 => memcpy8!(src, dst, "" ",8" ",16" ",24" ",32" ",40" ",48"),
            8 => memcpy8!(src, dst, "" ",8" ",16" ",24" ",32" ",40" ",48" ",56"),
            _ => unreachable!(),
        }
    }
}
#[inline]
unsafe fn memcpy16_const(src: *const u8, dst: *mut u8, size: usize) {
    unsafe {
        match size {
            1 => memcpy16!(src, dst, ""),
            2 => memcpy16!(src, dst, "" ",16"),
            3 => memcpy16!(src, dst, "" ",16" ",32"),
            4 => memcpy16!(src, dst, "" ",16" ",32" ",48"),
            5 => memcpy16!(src, dst, "" ",16" ",32" ",48" ",64"),
            6 => memcpy16!(src, dst, "" ",16" ",32" ",48" ",64" ",80"),
            7 => memcpy16!(src, dst, "" ",16" ",32" ",48" ",64" ",80" ",96"),
            8 => memcpy16!(src, dst, "" ",16" ",32" ",48" ",64" ",80" ",96" ",112"),
            _ => unreachable!(),
        }
    }
}
